/src/main/java/org/wildfly/example/rest/server/EchoResource.java=03d80b908ae51694853836eb7114dee0
/src/main/java/org/wildfly/example/rest/server/Main.java=5cbf7408d7918633fa69145987f0d675
/src/main/java/org/wildfly/example/rest/server/RestActivator.java=e3bae0645e077d49d47233019bf289be
