#
# Copyright The WildFly Authors
# SPDX-License-Identifier: Apache-2.0
#

/src/main/java/org/wildfly/example/web/ClientServlet.java=0516612e011c6b405b44be428dc14fae
/src/main/java/org/wildfly/example/web/rest/RestActivator.java=0f01f69ee5f9f90e2a67ffb4cc2eb9e5
